#ifndef SPEED_PID_CONFIG_H
#define SPEED_PID_CONFIG_H

/* Proven actor_spc gains; keep synchronized until actor_spc is retired. */
#define SPEED_PID_SWING_KP 0.01f
#define SPEED_PID_SWING_KI 0.0f
#define SPEED_PID_SWING_KD 0.0f
#define SPEED_PID_SWING_FEEDFORWARD (1.0f / 50.0f)

#define SPEED_PID_BUCKET_KP 0.003f
#define SPEED_PID_BUCKET_KI 0.0f
#define SPEED_PID_BUCKET_KD 0.0f
#define SPEED_PID_BUCKET_POSITIVE_FEEDFORWARD (1.0f / 61.0f)
#define SPEED_PID_BUCKET_NEGATIVE_FEEDFORWARD (1.0f / 36.5f)

#define SPEED_PID_STICK_KP 0.003f
#define SPEED_PID_STICK_KI 0.0f
#define SPEED_PID_STICK_KD 0.0f
#define SPEED_PID_STICK_POSITIVE_FEEDFORWARD (1.0f / 60.0f)
#define SPEED_PID_STICK_NEGATIVE_FEEDFORWARD (1.0f / 42.5f)

#define SPEED_PID_BOOM_KP 0.003f
#define SPEED_PID_BOOM_KI 0.0f
#define SPEED_PID_BOOM_KD 0.0f
#define SPEED_PID_BOOM_POSITIVE_FEEDFORWARD (1.0f / 30.0f)
#define SPEED_PID_BOOM_NEGATIVE_FEEDFORWARD (1.0f / 30.0f)

#endif /* SPEED_PID_CONFIG_H */
