#ifndef SPEED_PID_CONFIG_H
#define SPEED_PID_CONFIG_H

#define SPEED_PID_X1_KP 0.01f
#define SPEED_PID_X1_KI 0.0f
#define SPEED_PID_X1_KD 0.0f
#define SPEED_PID_X1_FEEDFORWARD (1.0f / 50.0f)

/* X2：铲斗，反馈速度为 -v_bucket */
#define SPEED_PID_X2_KP 0.003f
#define SPEED_PID_X2_KI 0.0f
#define SPEED_PID_X2_KD 0.0f
#define SPEED_PID_X2_POSITIVE_FEEDFORWARD (1.0f / 61.0f)
#define SPEED_PID_X2_NEGATIVE_FEEDFORWARD (1.0f / 36.5f)

/* Y1：小臂 */
#define SPEED_PID_Y1_KP 0.003f
#define SPEED_PID_Y1_KI 0.0f
#define SPEED_PID_Y1_KD 0.0f
#define SPEED_PID_Y1_POSITIVE_FEEDFORWARD (1.0f / 60.0f)
#define SPEED_PID_Y1_NEGATIVE_FEEDFORWARD (1.0f / 42.5f)

/* Y2：大臂 */
#define SPEED_PID_Y2_KP 0.003f
#define SPEED_PID_Y2_KI 0.0f
#define SPEED_PID_Y2_KD 0.0f
#define SPEED_PID_Y2_POSITIVE_FEEDFORWARD (1.0f / 30.0f)
#define SPEED_PID_Y2_NEGATIVE_FEEDFORWARD (1.0f / 30.0f)

#endif /* SPEED_PID_CONFIG_H */
